<article style="margin-top: 3%; margin-bottom: 3%;">
    <div class="container">        
        <h1 class="article-title">What are BIGO strengths?</h1>
        <p class="lead" style="text-align: center;">BIGO takes advantage of the validation data generated by gene enrichment analysis tools, providing new information which helps to enclose the results and to generate new conclusions. Concretely, BIGO generates a ranking of biological terms and a network that shows the hidden relationships between different genes collections.</p>

        <div class="row" style="padding-top: 20px; text-align: center; padding-bottom: 50px;">
            <div class="col-xs-6 col-sm-4">
                <p class="lead">
                    <a href="#enrichment" class="btn btn-description btn-lg"><img src="images/gene_enrichment_icon.jpg" class="article-strengths-btn-img" alt="Gene enrichment analysis"><br>Gene enrichment <br>analysis</a>
                </p>
            </div>
            <div class="col-xs-6 col-sm-4">
                <p class="lead">
                    <a href="#ranking" class="btn btn-description btn-lg"><img src="images/ranking_icon.jpg" class="article-strengths-btn-img" alt="Ranking"><br>Ranking of<br>biological terms</a>
                </p>
            </div>
            <div class="col-xs-6 col-sm-4">
                <p class="lead">
                    <a href="#webgraph" class="btn btn-description btn-lg"><img src="images/webgraph_icon.jpg" class="article-strengths-btn-img" alt="Graph"><br>Groups of<br>genes network</a>
                </p>
            </div>
        </div>

        <hr id="enrichment" style="margin-bottom: 80px;">

        <section class="row" style="padding-bottom: 50px;">
            <div class="col-xs-6 col-md-5" style="text-align: center;">
                <img style="width: 95%;" src="images/enrichment_analysis.gif" alt="Enrichment analysis">
            </div>
            <div class="col-xs-6 col-md-7">
                <h2>Gene enrichment <span class="text-muted">analysis</span></h2>
                <h5 style="font-weight: lighter; text-align: justify;">
                    Gene enrichment analysis's objective is to compile the biological terms that are related to a group of genes. Each biological term has associated a statistical measure, the p-value, showing the relevance of the relation between a biological term and the genes in a way that it determines if this relation comes about by chance or not.
                </h5>
                <h5 style="font-weight: bold; text-align: justify;">
                    BIGO is able to apply a gene enrichment analysis to several groups of genes or to receive enrichment analysis results from groups of genes as an input.
                </h5>
            </div>

        </section>

        <hr id="ranking" style="margin-bottom: 80px;">

        <section class="row" style="padding-bottom: 50px;">
            <div class="col-xs-6 col-md-5" style="text-align: center;">
                <img style="width: 95%;" src="images/ranking.gif" alt="Ranking filtered">
            </div>
            <div class="col-xs-6 col-md-7">
                <h2>Ranking of <span class="text-muted">biological terms</span></h2>
                <h5 style="font-weight: lighter; text-align: justify;">
                    A ranking of biological terms is generated from gene enrichment analysis results obtained from the groups of genes under study. The ascending order of that ranking is based on the number of groups of genes in which every biological term has been detected. The first elements of this ranking will allow us to focus the conclusions of the biological study on those terms that really distinguish a group of genes between others. In addition, the last terms of the ranking could be considered as stop-words, since they are very generic biological functions that appear in a large number of genes, so they should not be taken into account to obtain conclusions.
                </h5>
                <h5 style="font-weight: bold; text-align: justify;">
                    BIGO also provides the opportunity of modifying the results by means of new ranking thresholds or by filtering the biological terms.
                </h5>
            </div>
        </section>

        <hr id="webgraph" style="margin-bottom: 80px;">

        <section class="row" style="padding-bottom: 50px;">
            <div class="col-xs-6 col-md-5" style="text-align: center;">
                <img style="width: 95%;" src="images/graph.gif" alt="Webgraph filtered">
            </div>
            <div class="cols-xs-6 col-md-7">
                <h2>Groups of <span class="text-muted">genes network</span></h2>
                <h5 style="font-weight: lighter; text-align: justify;">
                    BIGO generates a network from the biological term ranking that represents the relationship between the groups of genes based on the number of biological terms they share. 
                </h5>
                <h5 style="font-weight: bold; text-align: justify;">
                    This graph is able to show groups of genes which are well-defined and independent from each other. Moreover, those closely related groups are also interesting, in case they do not share a high proportion of their genes or, in other case, to simplify results overlapping them.
                </h5>
            </div>
        </section>
        <hr>
    </div>
</article>